FROM --platform=linux/amd64 ubuntu:22.04

RUN apt update && apt upgrade -y
RUN apt install -y python3 python3-pip
#RUN python3 -m venv --copies .env          # venv em docker pode ser desnecessário na maioria dos casos.
#RUN source ./.env/bin/activate             # Cada RUN é executado em um novo shell e não estaria ativado no proximo RUN. (não usar está linha)
#RUN ./.env/bin/python3 -m pip install -r requirements.txt
RUN python3 -m pip install -r requirements.txt

#Copiando diretório onde está o dockerfile para a raiz da imagem que será construida.
COPY .. /app

WORKDIR /APP

ENV 


